exclude: '^$'
fail_fast: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.11'
    hooks:
      - id: ruff-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: no-commit-to-branch
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v2.3.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - types-docutils
          - types-setuptools
          - types-PyYAML
          - types-requests

ci:
  # To trigger manually, comment on a pull request with "pre-commit.ci autofix"
  autofix_prs: false
  autoupdate_schedule: "monthly"
